### ISSUE TITLE
Add ability to plot data

### ISSUE THREAD

**Issue by ostrosco** [ostrosco/comms-rs#11]
We would like the ability to plot spectrum and time domain sample data for analysis. We need to assess whether or not we can do this at run-time.

**Comment by Alex-Addy** [comment]
I found https://docs.rs/dataplotlib/0.1.3/dataplotlib/ which looks pretty straightforward to work with, downside is that it looks to be dead for 2 years.
For a first pass to make this issue works I think dumping stuff out to a file that gnuplotlib can read should be sufficient.

**Comment by ostrosco** [comment]
The [rtplot](https://github.com/ostrosco/rtplot) library should work to address this. I'm going to close this issue since I think the plan would be to integrate `rtplot` into `comms-rs` once it releases.
