### ISSUE TITLE
Repo fails to clone on Windows

### ISSUE THREAD

**Issue by Chris--B** [ostrosco/comms-rs#121]
[Windows is Anti-Prn](https://superuser.com/questions/613313/why-cant-we-make-con-prn-null-folder-in-windows)

The repo is nontrivial to clone and build on Windows until `src/prn.rs` is renamed.

**Comment by garbagetrash** [comment]
Pull the latest master and try again

**Comment by Chris--B** [comment]
Works fine on my end.
