### ISSUE TITLE
Make random number generator nodes

### ISSUE THREAD

**Issue by garbagetrash** [ostrosco/comms-rs#16]
For now support for three specific node types would be nice:
- Some node to do 0 and 1 generation, u8 output
- Uniform random variable node, should support start and stop range parameters for node init()
- Gaussian random variable node, should support mean and standard deviation parameters (mu and sigma)

These would be nice in and of themselves, but they can also serve as very basic node examples for the less rust inclined developers to model their nodes after.  As such they should display 'best practice' and whatever that means for our team.

**Comment by Alex-Addy** [comment]
I am willing to make the random uniform distribution node. And I will do gaussian if rand supports it while I am at it.

**Comment by Alex-Addy** [comment]
What do you mean by 0-1 generation?

**Comment by Alex-Addy** [comment]
Looks like @ostrosco already did some work on #17

**Comment by garbagetrash** [comment]
This looks done, correct me if I'm wrong.
