### ISSUE TITLE
Make Mixer Node

### ISSUE THREAD

**Issue by garbagetrash** [ostrosco/comms-rs#21]
This should be pretty straightforward.  We need to be able mix things up and down in frequency with the software equivalent of an oscillator.

![codecogseqn 1](https://user-images.githubusercontent.com/43052613/46054144-49adf500-c103-11e8-94a1-2e54f44097f9.gif)

Likely this is the type of operation we'll want to run as a batch in a real system, so make sure to include support for both sample by sample processing as well as batch processing.

**Comment by garbagetrash** [comment]
This should be an easy kill, I'll do it in the next couple of days.

**Comment by ostrosco** [comment]
Closed by #53.
