### ISSUE TITLE
Create contribution guide

### ISSUE THREAD

**Issue by rfdoell** [ostrosco/comms-rs#5]
A contribution guide should be created and documented in the project so that new developers know how best to provide code to the comms-rs project.

Acceptance:
 * Guide created
 * Location of guide documented in the README
 * Example of workflow documented in the guide demonstrated on GitHub
 * Example referenced in guide somewhere

**Comment by ostrosco** [comment]
I'm curious as to what depth we should go into here. My gut says our contribution guide would be pretty simple?

- Use the GitFlow workflow.
- Write unit tests for new code being committed.
- Run `cargo clippy` and `cargo fmt` on code prior to issuing a pull request.

Is there anything else that people think I might be missing? @Alex-Addy any thoughts?

**Comment by Alex-Addy** [comment]
Keep it simple. Just a few bullet points should be sufficient to set expectations. We can make a more complicated guide if we ever try to open up development.

**Comment by ostrosco** [comment]
Added as part of #30.
